# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4
      - image: dwmkerr/dynamodb

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements-dev.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv env
            . env/bin/activate
            pip install -r requirements-dev.txt

      - save_cache:
          paths:
            - ./env
          key: v1-dependencies-{{ checksum "requirements-dev.txt" }}
        
      # run tests!
      - run:
          name: run tests
          command: |
            . env/bin/activate
            nosetests --with-coverage

      # run coveralls!
      - run:
          name: coveralls
          command: |
            . env/bin/activate
            coveralls
          when: on_success

      - store_artifacts:
          path: test-reports
          destination: test-reports
